* Roadmap
  - Fecha de entrega 06/08/16

** DONE Driver anemometro
La idea es que el usuario pueda ver desde su computador :smile: la velocidad
del viento.
*** HOLA MUNDO
     - [X] Conectar la placa con el sensor y leerlo con la
       sAPI(baremetalmente hablando)
     - [X] Conectar la placa con el sensor y leerlo utilizando FreeRTOS(una
       tarea o dos como mucho)
*** Disenio de la capa DRIVER

**** DONE Tenemos la siguiente estructura para implementar
      - [X] Controller
      Tarea periodica de 1 segundo que envia una senial de tiempo a las
      tareas que la escuchan
      - [X] Anemometer
      Tarea que realiza la lectura y calculo de velocidad. Se actualiza
      cuando Controller le envia la senial que ha llegado el tiempo
      - [X] Gatekeeper
      Recibe los mensajes de las diferentes tareas y los administra
      - [X] WindRose
      Tarea que realiza la lectura del sensor y calcula la direccion del
      viento. Deberia comunicar el valor a WindRoseLeds
      - [X] WindRoseLeds
      Toma el valor calculado por WindRose y enciende los leds que
      corresponden. Ver cual es la mejor manera de comunicar con WindRose
** TODO Informe
*** Caratula y makefiles
    - [X] Hacer la Caratula y el makefile
    - [ ] Seccion Introduccion
    - [ ] Seccion Disenio
    - [ ] Seccion Desarrollo
    - [ ] Seccion implementacion
    - [ ] Seccion Resultados
